name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    uses: ObsidianPublisher/actions/.github/workflows/deploy.yml@main
    with:
      GENERATE_GRAPH: false
    secrets:
      NETLIFY_HOOK: ${{ secrets.NETLIFY_HOOK }}
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}