group:
  - files:
      - source: template/index.yml
        dest: .github/workflows/index.yml
      - source: template/maintenance.yml
        dest: .github/workflows/maintenance.yml
      - source: template/update.yml
        dest: .github/workflows/update.yml
    repos: |
      ObsidianPublisher/template-gh-pages
      ObsidianPublisher/template-netlify-vercel
  - files:
      - sources: template/gh-pages/
        dest: .github/workflows
    repos: |
      ObsidianPublisher/template-gh-pages
  - files:
      - sources: template/netlify/
        dest: .github/workflows
    repos: |
      ObsidianPublisher/template-netlify-vercel

