group:
  - files:
      - source: template/index.yml
        dest: .github/workflows/index.yml
      - source: template/maintenance.yml
        dest: .github/workflows/maintenance.yml
      - source: template/update.yml
        dest: .github/workflows/update.yml
    repos: |
      ObsidianPublisher/template-gh-pages
      ObsidianPublisher/template-netlify-vercel
  - files:
      - source: template/gh-pages/deploy.yml
        dest: .github/workflows
      - source: template/gh-pages/.env
        dest: .github
    repos: |
      ObsidianPublisher/template-gh-pages
  - files:
      - source: template/netlify/deploy.yml
        dest: .github/workflows
      - source: template/netlify/.env
        dest: .github/.env.netlify
      - source: template/vercel/.env
        dest: .github/.env.vercel
    repos: |
      ObsidianPublisher/template-netlify-vercel

