name: Repository maintenance
on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
jobs:
  unused-images:
    runs-on: ubuntu-latest
    outputs:
      workflow-type: ${{ steps.check-env.outputs.WORKFLOW_TYPE }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
      - name: Get .env file
        uses: xom9ikk/dotenv@v2.2.0
        with:
          path: .github
          load-mode: strict
      - name: Outputs environment
        id: check-env
        run: |
          echo "WORKFLOW_TYPE=${{ env.WORKFLOW_TYPE }}" >> $GITHUB_OUTPUT
          echo "ACT=${{ env.ACT }}" >> $GITHUB_OUTPUT
      - name: Clean unused images
        if: env.CLEAN == 'true'
        run: |
          echo "CLEAN UNUSED IMAGES"
          pip install mkdocs mkdocs-material Babel
          python find_unused_media.py
      - name: Git commit and push
        if: env.CLEAN == 'true' && env.DRY_RUN == 'false' || !env.ACT 
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_PAT }}
  update-other:
    needs: unused-images
    runs-on: ubuntu-latest
    if: needs.unused-images.outputs.workflow-type != 'gh-pages'
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Update requirements
        run: |
          pip install pur
          isExist=false
          if [ -f "requirements_actions.txt" ]; then
            pur -r requirements_actions.txt
            isExist=true
          fi
          pur -r requirements.txt --skip obsidiantools
          echo "REQUIREMENTSACTIONS=$isExist" >> $GITHUB_ENV
      - name: Push updated requirements
        uses: actions-js/push@master
        if: ${{ !env.ACT }}
        with:
          github_token: ${{ secrets.GH_PAT }}
      - name: Check cache
        if: env.REQUIREMENTSACTIONS == 'true'
        id: cache
        uses: actions/cache@v3
        with:
          path: venv-other
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements_actions.txt') }}
      - if: steps.cache.outputs.cache-hit != 'true' && env.REQUIREMENTSACTIONS == 'true'
        name: Recreate cache
        run: |
          if [ -d "venv-other" ]; then rm -rf venv-other; fi
          python3 -m venv venv-other
          source venv-other/bin/activate
          pip install -r requirements_actions.txt
  update-gh-pages:
    needs: unused-images
    runs-on: ubuntu-latest
    if: needs.unused-images.outputs.workflow-type == 'gh-pages'
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Update requirements
        run: |
          pip install pur
          pur -r requirements.txt
      - name: Push updated requirements
        uses: actions-js/push@master
        if: ${{ !env.ACT }}
        with:
          github_token: ${{ secrets.GH_PAT }}
      - name: Check cache
        id: cache
        uses: actions/cache@v3
        with:
          path: venv
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        name: Recreate cache
        run: |
          if [ -d "venv" ]; then rm -rf venv; fi
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
